[programs.devnet]
myepicproject = "97PEGbbCDA53kaG4xYLxELWVEATonz4i8b1E8RNKxCAe"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/Users/maddy/.config/solana/id.json"

[scripts]
test = "node tests/myepicproject.js"
